name: test

on:
  pull_request:
    branches:
      - master
      - develop

env:
  cache-version: v2

jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-node-

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: lint
      run: yarn lint:check

    - name: test
      run: yarn test

    - name: build
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MICRO_CMS: ${{ secrets.MICRO_CMS }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      run: yarn generate:static
