name: test

on:
  pull_request:
    branches:
      - master
      - develop

env:
  cache-version: v4

jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}-node-

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: lint
      run: yarn lint:check

    - name: test
      run: yarn test

    # Storybookをビルド
    - name: build Storybook
      run: yarn build-storybook

    # Nuxtをビルド
    - name: create .env file
      run: echo "${{ secrets.ENV_FIREBASE }}" > .env

    - name: build
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MICRO_CMS: ${{ secrets.MICRO_CMS }}
      run: yarn generate
