name: test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    #- name: lint
    #  run: yarn lint

    - name: test
      run: yarn test

    - name: build
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MICRO_CMS: ${{ secrets.MICRO_CMS }}
      run: yarn generate:static
